- loans/SOLUTIONS.md
This problem was solved with Java and Spring Boot Starter Web
> doc: Add new loan problem solution

- secure-password/SOLUTIONS.md
Adding secure-password solution with Spring WebFlux
> Adding secure-password solution

- cryptography/SOLUTIONS.md
Adding cryptography solution with .NET
> Add link to cryptography solution

- loans/SOLUTIONS.md
Adiciona uma solução para o desafio de emprestimos escrita em typescript.
> doc: solution to loans challenge

- cryptography/SOLUTIONS.md
Realizado desafio em Java com Spring e, se for suficiente e adequado, para exemplos de soluções. 
Se existirem sugestões, criticas ou possíveis gaps no projeto, quaisquer que seja, é bem vindo e vai ser muito construtivo para meu aprendizado na área.
> Doc: new solution in Java/Spring

- url-shortener/SOLUTIONS.md
Nova solução em Go para o desafio de Encurtador de URLs
> Doc: new solution in Go

- cryptography/SOLUTIONS.md
minha solução do desafio de criptografia
> my solution

- secure-password/SOLUTIONS.md
Updated SOLUTIONS.md for the secure-password challenge with my solution implemented in C#.
> Added solution implemented in C# to the SOLUTIONS.md file for the secure-password challenge.

- cryptography/SOLUTIONS.md
- loans/SOLUTIONS.md
Boa noite!
Minha solução para o desafio de empréstimos utilizando Java/Spring.
> Solução Desafio Empréstimos

- cryptography/SOLUTIONS.md
- loans/SOLUTIONS.md
- points-of-interest/SOLUTIONS.md
- secure-password/SOLUTIONS.md
- url-shortener/SOLUTIONS.md
There seems to be a lack of solutions using C#, so I'm here to strengthen the .NET community! 😁
> Updated SOLUTIONS.md for all challenges, including solutions using C#.

- loans/SOLUTIONS.md
Enviando minha solução para o desafio "Empréstimos".
> feat(loans): add HenriqueSilverio/Loans.TypeScript solution

- loans/SOLUTIONS.md
> Update SOLUTIONS.md add josehenriquepg solution

- secure-password/SOLUTIONS.md
My solution for "Secure Password" challenge implemented using Typescript.
> Secure Password typescript solution

- authentication/PROBLEM.md
- authentication/SOLUTIONS.md
- secure-password/SOLUTIONS.md
Novo desafio relacionado a autenticação
> Novo desafio authentication

- secure-password/SOLUTIONS.md
Secure-Password challenge using TypeScript.
> feat(secure-password): add JuanLucca846/secure-password.TypeScript

- authentication/SOLUTIONS.md
Minha solução para o desafio de autenticação
> Soluções - Autenticação

- url-shortener/SOLUTIONS.md
Minha solução para o encurtador de URL usando **Java** com **_Spring Boot_**
Link: https://github.com/andre-xizto/encurtador-url
> Solução para o problema de encurtador de url

- points-of-interest/SOLUTIONS.md
- secure-password/SOLUTIONS.md
Minha solução para o desafio "points-of-interest" usando **Java** com _**Spring Boot**_
Link: https://github.com/andre-xizto/points-of-interest
> Solution in Java

- authentication/SOLUTIONS.md
- cryptography/SOLUTIONS.md
> feat: add ruby solution to authentication and cripto

- authentication/SOLUTIONS.md
Authentication with Javascript
> desafio authentication em Javascript

- cryptography/PROBLEM.md
> doc: Update PROBLEM.md for cryptography challenge

- loans/SOLUTIONS.md
Add a new Go solution for Loan challenge.
> doc: Add new Go solution for loans

- loans/SOLUTIONS.md
Olá, gostaria de sugerir a adição da minha solução para o desafio de empréstimos (Loans) do repositório.
🚀 Tecnologias utilizadas
Java 21
Spring Boot
Maven
JUnit 5
Mockito
🔗 Link da solução
https://github.com/caio20538/loans.git
✅ Funcionalidades implementadas
Endpoint /customer-loans com regras de negócio completas.
Validação das regras conforme o problema.
Testes unitários cobrindo as regras com JUnit 5 e Mockito.
Código limpo, organizado, seguindo boas práticas, arquitetura REST e princípios SOLID.
📜 Observações
Caso haja qualquer feedback ou melhoria a ser feita, estou totalmente aberto para ajustes.
🔥 Checklist
✅O repositório está público
✅README.md contendo descrição do projeto, execução e testes
✅O desafio está implementado conforme o enunciado
🤝 Agradecimento
Agradeço pela …
> doc: Update SOLUTIONS.md

- points-of-interest/SOLUTIONS.md
Minha solicitação para o desafio points-of-interest
> Update SOLUTIONS.md com minha solucao
